good
else
finally
raised ValueError as expected
